name: drupal-php73

volumes:
  www:

services:
  dev:
    hostname: drupal-php73
    build: dev
    volumes:
      - www:/var/www
      - ./.gitconfig:/root/.gitconfig
    depends_on:
      - apache
  apache:
    image: httpd
    ports:
      - 8073:80
