name: drupal-php74

volumes:
  www:

services:
  dev:
    hostname: drupal-php74
    build: dev
    volumes:
      - ./www:/var/www
    depends_on:
      - apache
  apache:
    image: httpd
    ports:
      - 8074:80
