name: drupal-php74

services:
  dev:
    hostname: drupal-php74
    build: dev
    volumes:
      - ./www:/var/www
    depends_on:
      - apache
  apache:
    build: apache
    volumes:
      - ./www:/var/www
      - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - 8074:80
