name: drupal-php81

volumes:
  www:
  ssh:
  vscode-server:
  mysql:
  sites-available:
  sites-enabled:

services:
  drupal:
    hostname: drupal-php81
    build:
      context: .
      args:
        UBUNTU_MIRROR: ${UBUNTU_MIRROR:-http://mirror.xtom.com.hk/ubuntu/}
    environment:
      GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME}
      GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL}
    volumes:
      - www:/var/www
      - ssh:/root/.ssh
      - vscode-server:/root/.vscode-server
      - sites-available:/etc/apache2/sites-available
      - sites-enabled:/etc/apache2/sites-enabled
    ports:
      - 8081:80
      - 2281:22
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3081:3306
