name: drupal-php73

volumes:
  www:
  root:
  mysql:
  sites-available:
  sites-enabled:

services:
  drupal:
    hostname: drupal-php73
    build:
      context: .
      args:
        UBUNTU_MIRROR: ${UBUNTU_MIRROR:-http://mirror.xtom.com.hk/ubuntu/}
    volumes:
      - www:/var/www
      - root:/root
      - sites-available:/etc/apache2/sites-available
      - sites-enabled:/etc/apache2/sites-enabled
    ports:
      - 8073:80
      - 2273:22
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3373:3306
