name: {{name}}

volumes:
  www:

services:
  dev:
    hostname: {{name}}
    build: dev
    volumes:
      - ./www:/var/www
    depends_on:
      - apache
  apache:
    image: httpd
    ports:
      - {{apache_port}}:80
