name: {{name}}

volumes:
  www:
  ssh:
  vscode-server:
  mysql:

services:
  drupal:
    hostname: {{name}}
    build:
      context: .
      args:
        UBUNTU_MIRROR: ${UBUNTU_MIRROR:-http://mirror.xtom.com.hk/ubuntu/}
    environment:
      GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME}
      GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL}
    volumes:
      - www:/var/www
      - ssh:/root/.ssh
      - vscode-server:/root/.vscode-server
      - ./vhosts:/etc/apache2/vhosts
    ports:
      - {{apache_port}}:80
      - {{ssh_port}}:22
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - {{mariadb_port}}:3306
