name: drupal-php80

volumes:
  www:

services:
  dev:
    hostname: drupal-php80
    build: dev
    volumes:
      - ./www:/var/www
    depends_on:
      - apache
  apache:
    image: httpd
    ports:
      - 8080:80
