name: drupal-php80

volumes:
  www:
  ssh:
  vscode-server:
  mysql:

services:
  drupal:
    hostname: drupal-php80
    build: .
    env_file: variables.env
    volumes:
      - www:/var/www
      - ssh:/root/.ssh
      - vscode-server:/root/.vscode-server
      - ./vhosts:/etc/apache2/vhosts
    ports:
      - 8080:80
      - 2280:22
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
    command: --transaction-isolation=READ-COMMITTED
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3080:3306
