name: drupal-php81

volumes:
  www:

services:
  dev:
    hostname: drupal-php81
    build: dev
    volumes:
      - www:/var/www
      - ./.gitconfig:/root/.gitconfig
    depends_on:
      - apache
  apache:
    image: httpd
    ports:
      - 8081:80
